openapi: 3.0.1
info:
  contact:
    email: it@vilabs.eu
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: wabli-deploy-test
  url: https://83.212.100.226:4008/v1
security:
- {}
tags:
- description: not yet ready
  name: user
- description: not yet ready
  name: august
- description: not yet ready
  name: september
- description: not yet ready
  name: october
- description: not yet ready
  name: november
- description: not yet ready
  name: december
paths:
  /user:
    post:
      operationId: createuser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
          description: successful operation
      summary: Creates the data
      tags:
      - user
      x-eov-operation-handler: controllers/UserController
  /user/{userId}:
    delete:
      operationId: deleteuser
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - user
      x-eov-operation-handler: controllers/UserController
    get:
      operationId: getuser
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
          description: successful operation
      summary: Get the element
      tags:
      - user
      x-eov-operation-handler: controllers/UserController
    put:
      operationId: updateuser
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
          description: successful operation
      summary: Updates the element
      tags:
      - user
      x-eov-operation-handler: controllers/UserController
  /user/getAll:
    get:
      operationId: getAlluser
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/user'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - user
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/UserController
  /user/getByParams:
    get:
      operationId: getByParamsuser
      parameters:
      - description: the query based on which the search is performed
        explode: true
        in: query
        name: filter
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/user'
                type: array
          description: successful operation
      summary: Get all the data based on user query
      tags:
      - user
      x-method-get-by-params: "true"
      x-eov-operation-handler: controllers/UserController
  /august:
    post:
      operationId: createaugust
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/august'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/august'
          description: successful operation
      summary: Creates the data
      tags:
      - august
      x-eov-operation-handler: controllers/AugustController
  /august/{augustId}:
    delete:
      operationId: deleteaugust
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: augustId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - august
      x-eov-operation-handler: controllers/AugustController
    get:
      operationId: getaugust
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: augustId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/august'
          description: successful operation
      summary: Get the element
      tags:
      - august
      x-eov-operation-handler: controllers/AugustController
    put:
      operationId: updateaugust
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: augustId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/august'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/august'
          description: successful operation
      summary: Updates the element
      tags:
      - august
      x-eov-operation-handler: controllers/AugustController
  /august/getAll:
    get:
      operationId: getAllaugust
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/august'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - august
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/AugustController
  /august/getByParams:
    get:
      operationId: getByParamsaugust
      parameters:
      - description: the query based on which the search is performed
        explode: true
        in: query
        name: filter
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/august'
                type: array
          description: successful operation
      summary: Get all the data based on user query
      tags:
      - august
      x-method-get-by-params: "true"
      x-eov-operation-handler: controllers/AugustController
  /september:
    post:
      operationId: createseptember
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/september'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/september'
          description: successful operation
      summary: Creates the data
      tags:
      - september
      x-eov-operation-handler: controllers/SeptemberController
  /september/{septemberId}:
    delete:
      operationId: deleteseptember
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: septemberId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - september
      x-eov-operation-handler: controllers/SeptemberController
    get:
      operationId: getseptember
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: septemberId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/september'
          description: successful operation
      summary: Get the element
      tags:
      - september
      x-eov-operation-handler: controllers/SeptemberController
    put:
      operationId: updateseptember
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: septemberId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/september'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/september'
          description: successful operation
      summary: Updates the element
      tags:
      - september
      x-eov-operation-handler: controllers/SeptemberController
  /september/getAll:
    get:
      operationId: getAllseptember
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/september'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - september
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/SeptemberController
  /september/getByParams:
    get:
      operationId: getByParamsseptember
      parameters:
      - description: the query based on which the search is performed
        explode: true
        in: query
        name: filter
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/september'
                type: array
          description: successful operation
      summary: Get all the data based on user query
      tags:
      - september
      x-method-get-by-params: "true"
      x-eov-operation-handler: controllers/SeptemberController
  /october:
    post:
      operationId: createoctober
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/october'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/october'
          description: successful operation
      summary: Creates the data
      tags:
      - october
      x-eov-operation-handler: controllers/OctoberController
  /october/{octoberId}:
    delete:
      operationId: deleteoctober
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: octoberId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - october
      x-eov-operation-handler: controllers/OctoberController
    get:
      operationId: getoctober
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: octoberId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/october'
          description: successful operation
      summary: Get the element
      tags:
      - october
      x-eov-operation-handler: controllers/OctoberController
    put:
      operationId: updateoctober
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: octoberId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/october'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/october'
          description: successful operation
      summary: Updates the element
      tags:
      - october
      x-eov-operation-handler: controllers/OctoberController
  /october/getAll:
    get:
      operationId: getAlloctober
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/october'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - october
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/OctoberController
  /october/getByParams:
    get:
      operationId: getByParamsoctober
      parameters:
      - description: the query based on which the search is performed
        explode: true
        in: query
        name: filter
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/october'
                type: array
          description: successful operation
      summary: Get all the data based on user query
      tags:
      - october
      x-method-get-by-params: "true"
      x-eov-operation-handler: controllers/OctoberController
  /november:
    post:
      operationId: createnovember
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/november'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/november'
          description: successful operation
      summary: Creates the data
      tags:
      - november
      x-eov-operation-handler: controllers/NovemberController
  /november/{novemberId}:
    delete:
      operationId: deletenovember
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: novemberId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - november
      x-eov-operation-handler: controllers/NovemberController
    get:
      operationId: getnovember
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: novemberId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/november'
          description: successful operation
      summary: Get the element
      tags:
      - november
      x-eov-operation-handler: controllers/NovemberController
    put:
      operationId: updatenovember
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: novemberId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/november'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/november'
          description: successful operation
      summary: Updates the element
      tags:
      - november
      x-eov-operation-handler: controllers/NovemberController
  /november/getAll:
    get:
      operationId: getAllnovember
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/november'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - november
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/NovemberController
  /november/getByParams:
    get:
      operationId: getByParamsnovember
      parameters:
      - description: the query based on which the search is performed
        explode: true
        in: query
        name: filter
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/november'
                type: array
          description: successful operation
      summary: Get all the data based on user query
      tags:
      - november
      x-method-get-by-params: "true"
      x-eov-operation-handler: controllers/NovemberController
  /december:
    post:
      operationId: createdecember
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/december'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/december'
          description: successful operation
      summary: Creates the data
      tags:
      - december
      x-eov-operation-handler: controllers/DecemberController
  /december/{decemberId}:
    delete:
      operationId: deletedecember
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: decemberId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - december
      x-eov-operation-handler: controllers/DecemberController
    get:
      operationId: getdecember
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: decemberId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/december'
          description: successful operation
      summary: Get the element
      tags:
      - december
      x-eov-operation-handler: controllers/DecemberController
    put:
      operationId: updatedecember
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: decemberId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/december'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/december'
          description: successful operation
      summary: Updates the element
      tags:
      - december
      x-eov-operation-handler: controllers/DecemberController
  /december/getAll:
    get:
      operationId: getAlldecember
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/december'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - december
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/DecemberController
  /december/getByParams:
    get:
      operationId: getByParamsdecember
      parameters:
      - description: the query based on which the search is performed
        explode: true
        in: query
        name: filter
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/december'
                type: array
          description: successful operation
      summary: Get all the data based on user query
      tags:
      - december
      x-method-get-by-params: "true"
      x-eov-operation-handler: controllers/DecemberController
components:
  schemas:
    user:
      example:
        _id: _id
        userName: userName
        userSurname: userSurname
      properties:
        _id:
          type: string
        userName:
          type: string
        userSurname:
          type: string
      required:
      - userName
      - userSurname
      type: object
    august:
      example:
        day19: day19
        employee: ""
        day18: day18
        day17: day17
        day16: day16
        day15: day15
        day14: day14
        day13: day13
        day8: day8
        day12: day12
        day9: day9
        day11: day11
        day22: day22
        day6: day6
        day10: day10
        day21: day21
        day7: day7
        day20: day20
        day4: day4
        day5: day5
        day2: day2
        day3: day3
        _id: _id
        day1: day1
      properties:
        _id:
          type: string
        employee:
          oneOf:
          - $ref: '#/components/schemas/user'
          - type: string
          x-one-of-name: user
        day1:
          type: string
        day2:
          type: string
        day3:
          type: string
        day4:
          type: string
        day5:
          type: string
        day6:
          type: string
        day7:
          type: string
        day8:
          type: string
        day9:
          type: string
        day10:
          type: string
        day11:
          type: string
        day12:
          type: string
        day13:
          type: string
        day14:
          type: string
        day15:
          type: string
        day16:
          type: string
        day17:
          type: string
        day18:
          type: string
        day19:
          type: string
        day20:
          type: string
        day21:
          type: string
        day22:
          type: string
      required:
      - day1
      - day10
      - day11
      - day12
      - day13
      - day14
      - day15
      - day16
      - day17
      - day18
      - day19
      - day2
      - day20
      - day21
      - day22
      - day3
      - day4
      - day5
      - day6
      - day7
      - day8
      - day9
      - employee
      type: object
    september:
      example:
        septDay17: septDay17
        septDay18: septDay18
        septDay19: septDay19
        septDay13: septDay13
        septDay14: septDay14
        septDay15: septDay15
        septDay16: septDay16
        septDay20: septDay20
        septDay10: septDay10
        septDay21: septDay21
        septDay11: septDay11
        septDay12: septDay12
        septDay8: septDay8
        septDay9: septDay9
        septDay6: septDay6
        septDay7: septDay7
        septDay4: septDay4
        septDay5: septDay5
        septDay2: septDay2
        septDay3: septDay3
        septDay1: septDay1
        _id: _id
        employeeSept: ""
      properties:
        _id:
          type: string
        employeeSept:
          oneOf:
          - $ref: '#/components/schemas/user'
          - type: string
          x-one-of-name: user
        septDay1:
          type: string
        septDay2:
          type: string
        septDay3:
          type: string
        septDay4:
          type: string
        septDay5:
          type: string
        septDay6:
          type: string
        septDay7:
          type: string
        septDay8:
          type: string
        septDay9:
          type: string
        septDay10:
          type: string
        septDay11:
          type: string
        septDay12:
          type: string
        septDay13:
          type: string
        septDay14:
          type: string
        septDay15:
          type: string
        septDay16:
          type: string
        septDay17:
          type: string
        septDay18:
          type: string
        septDay19:
          type: string
        septDay20:
          type: string
        septDay21:
          type: string
      required:
      - employeeSept
      - septDay1
      - septDay10
      - septDay11
      - septDay12
      - septDay13
      - septDay14
      - septDay15
      - septDay16
      - septDay17
      - septDay18
      - septDay19
      - septDay2
      - septDay20
      - septDay21
      - septDay3
      - septDay4
      - septDay5
      - septDay6
      - septDay7
      - septDay8
      - septDay9
      type: object
    october:
      example:
        octDay16: octDay16
        employeeOct: ""
        octDay15: octDay15
        octDay18: octDay18
        octDay17: octDay17
        octDay2: octDay2
        octDay3: octDay3
        octDay10: octDay10
        octDay21: octDay21
        octDay1: octDay1
        octDay20: octDay20
        octDay12: octDay12
        octDay11: octDay11
        octDay22: octDay22
        octDay14: octDay14
        octDay13: octDay13
        octDay8: octDay8
        _id: _id
        octDay9: octDay9
        octDay6: octDay6
        octDay7: octDay7
        octDay4: octDay4
        octDay5: octDay5
      properties:
        _id:
          type: string
        employeeOct:
          oneOf:
          - $ref: '#/components/schemas/user'
          - type: string
          x-one-of-name: user
        octDay1:
          type: string
        octDay2:
          type: string
        octDay3:
          type: string
        octDay4:
          type: string
        octDay5:
          type: string
        octDay6:
          type: string
        octDay7:
          type: string
        octDay8:
          type: string
        octDay9:
          type: string
        octDay10:
          type: string
        octDay11:
          type: string
        octDay12:
          type: string
        octDay13:
          type: string
        octDay14:
          type: string
        octDay15:
          type: string
        octDay16:
          type: string
        octDay17:
          type: string
        octDay18:
          type: string
        octDay20:
          type: string
        octDay21:
          type: string
        octDay22:
          type: string
      required:
      - employeeOct
      - octDay1
      - octDay10
      - octDay11
      - octDay12
      - octDay13
      - octDay14
      - octDay15
      - octDay16
      - octDay17
      - octDay18
      - octDay2
      - octDay20
      - octDay21
      - octDay22
      - octDay3
      - octDay4
      - octDay5
      - octDay6
      - octDay7
      - octDay8
      - octDay9
      type: object
    november:
      example:
        novDay9: novDay9
        novDay7: novDay7
        novDay8: novDay8
        novDay16: novDay16
        novDay17: novDay17
        novDay18: novDay18
        novDay19: novDay19
        novDay12: novDay12
        novDay13: novDay13
        novDay14: novDay14
        novDay15: novDay15
        novDay5: novDay5
        novDay6: novDay6
        novDay20: novDay20
        novDay3: novDay3
        novDay10: novDay10
        novDay21: novDay21
        _id: _id
        novDay4: novDay4
        novDay11: novDay11
        novDay22: novDay22
        novDay1: novDay1
        employeeNov: ""
        novDay2: novDay2
      properties:
        _id:
          type: string
        novDay1:
          type: string
        novDay2:
          type: string
        novDay3:
          type: string
        novDay4:
          type: string
        novDay5:
          type: string
        novDay6:
          type: string
        novDay7:
          type: string
        novDay8:
          type: string
        novDay9:
          type: string
        novDay10:
          type: string
        novDay11:
          type: string
        novDay12:
          type: string
        novDay13:
          type: string
        novDay14:
          type: string
        novDay15:
          type: string
        novDay16:
          type: string
        novDay17:
          type: string
        novDay18:
          type: string
        novDay19:
          type: string
        novDay20:
          type: string
        novDay21:
          type: string
        novDay22:
          type: string
        employeeNov:
          oneOf:
          - $ref: '#/components/schemas/user'
          - type: string
          x-one-of-name: user
      required:
      - employeeNov
      - novDay1
      - novDay10
      - novDay11
      - novDay12
      - novDay13
      - novDay14
      - novDay15
      - novDay16
      - novDay17
      - novDay18
      - novDay19
      - novDay2
      - novDay20
      - novDay21
      - novDay22
      - novDay3
      - novDay4
      - novDay5
      - novDay6
      - novDay7
      - novDay8
      - novDay9
      type: object
    december:
      example:
        decDay6: decDay6
        decDay7: decDay7
        decDay8: decDay8
        decDay9: decDay9
        decDay2: decDay2
        decDay19: decDay19
        decDay3: decDay3
        decDay4: decDay4
        decDay17: decDay17
        decDay5: decDay5
        decDay18: decDay18
        decDay1: decDay1
        employeeDec: ""
        decDay15: decDay15
        decDay16: decDay16
        decDay13: decDay13
        _id: _id
        decDay14: decDay14
        decDay11: decDay11
        decDay12: decDay12
        decDay20: decDay20
        decDay10: decDay10
        decDay21: decDay21
      properties:
        _id:
          type: string
        decDay1:
          type: string
        decDay2:
          type: string
        decDay3:
          type: string
        decDay4:
          type: string
        decDay5:
          type: string
        decDay6:
          type: string
        decDay7:
          type: string
        decDay8:
          type: string
        decDay9:
          type: string
        decDay10:
          type: string
        decDay11:
          type: string
        decDay12:
          type: string
        decDay13:
          type: string
        decDay14:
          type: string
        decDay15:
          type: string
        decDay16:
          type: string
        decDay17:
          type: string
        decDay18:
          type: string
        decDay19:
          type: string
        decDay20:
          type: string
        decDay21:
          type: string
        employeeDec:
          oneOf:
          - $ref: '#/components/schemas/user'
          - type: string
          x-one-of-name: user
      required:
      - decDay1
      - decDay10
      - decDay11
      - decDay12
      - decDay13
      - decDay14
      - decDay15
      - decDay16
      - decDay17
      - decDay18
      - decDay19
      - decDay2
      - decDay20
      - decDay21
      - decDay3
      - decDay4
      - decDay5
      - decDay6
      - decDay7
      - decDay8
      - decDay9
      - employeeDec
      type: object
